apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rivora.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rivora.controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "rivora.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rivora.controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rivora.controller.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: rivora-controller
          image: "{{ .Values.image.controller.repository }}:{{ .Values.image.controller.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.controller.pullPolicy }}
          args:
            - -loadbalancer-class={{ .Values.controller.loadBalancerClass }}
            - -workers={{ .Values.controller.workers }}
            - -gateway-api={{ .Values.gatewayApi.enabled }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
