{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rivora.fullname" . }}-controller
  labels:
    {{- include "rivora.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rivora.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "rivora.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
