apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rivora.fullname" . }}-rivorad
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rivora.rivorad.labels" . | nindent 4 }}
type: Opaque
stringData:
  RIVORA_API_KEY: {{ .Values.rivorad.apiKey | quote }}
  RIVORA_API_READONLY_KEY: {{ .Values.rivorad.apiReadOnlyKey | quote }}
  RIVORA_TLS_SELF_SIGNED: {{ .Values.rivorad.tls.selfSigned | ternary "1" "" | quote }}
  RIVORA_TLS_CERT: {{ .Values.rivorad.tls.cert | quote }}
  RIVORA_TLS_KEY: {{ .Values.rivorad.tls.key | quote }}
